######## Recommend Service

# Default: 8980, which port to create the server
servicePort: 8980

# Default: null, open a port for prometheus monitoring tool, if set, user can check the
# performance using prometheus
monitorPort: 1237

# default: null, must be provided, item column name
itemIDColumn: tweet_id

# default: null, must be provided, column names for inference, order related.
inferenceColumns: engaged_with_user_is_verified, enaging_user_is_verified, present_media_language, present_media, tweet_type, language, engaged_with_user_follower_count, engaged_with_user_following_count, enaging_user_follower_count, enaging_user_following_count, len_hashtags, len_domains, len_links

# default: localhost:8980, recall service target
recallServiceURL: localhost:8084

# default: localhost:8980, feature service target
featureServiceURL: localhost:8082

# default: localhost:8980, inference service target
rankingServiceURL: localhost:8083