apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  ports:
  - name: redisport
    port: 6379
  selector:
    app: analytics-zoo-ppml-trusted-realtime-ml-graphene
    component: master
