/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_zoo_pipeline_api_net_PytorchModel */

#ifndef _Included_com_intel_analytics_zoo_pipeline_api_net_PytorchModel
#define _Included_com_intel_analytics_zoo_pipeline_api_net_PytorchModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_zoo_pipeline_api_net_PytorchModel
 * Method:    loadNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_zoo_pipeline_api_net_PytorchModel_loadNative
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_intel_analytics_zoo_pipeline_api_net_PytorchModel
 * Method:    forwardNative
 * Signature: (J[FI[I)Lcom/intel/analytics/zoo/pipeline/inference/JTensor;
 */
JNIEXPORT jobject JNICALL Java_com_intel_analytics_zoo_pipeline_api_net_PytorchModel_forwardNative
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jintArray);

/*
 * Class:     com_intel_analytics_zoo_pipeline_api_net_PytorchModel
 * Method:    backwardNative
 * Signature: (J[FI[I)Lcom/intel/analytics/zoo/pipeline/inference/JTensor;
 */
JNIEXPORT jobject JNICALL Java_com_intel_analytics_zoo_pipeline_api_net_PytorchModel_backwardNative
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jintArray);

/*
 * Class:     com_intel_analytics_zoo_pipeline_api_net_PytorchModel
 * Method:    getGradientNative
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_intel_analytics_zoo_pipeline_api_net_PytorchModel_getGradientNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_zoo_pipeline_api_net_PytorchModel
 * Method:    updateWeightNative
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_zoo_pipeline_api_net_PytorchModel_updateWeightNative
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     com_intel_analytics_zoo_pipeline_api_net_PytorchModel
 * Method:    getWeightNative
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_intel_analytics_zoo_pipeline_api_net_PytorchModel_getWeightNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_zoo_pipeline_api_net_PytorchModel
 * Method:    releaseNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_zoo_pipeline_api_net_PytorchModel_releaseNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_zoo_pipeline_api_net_PytorchModel
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT int JNICALL Java_com_intel_analytics_zoo_pipeline_api_net_PytorchModel_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
