apiVersion: deviceplugin.intel.com/v1
kind: SgxDevicePlugin
metadata:
  name: sgxdeviceplugin-sample
spec:
  image: intel/intel-sgx-plugin:0.21.0
  initImage: intel/intel-sgx-initcontainer:0.21.0
  enclaveLimit: 110
  provisionLimit: 110
  logLevel: 4
  nodeSelector:
    feature.node.kubernetes.io/custom-intel.sgx: 'true'
