apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
spec:
  selector:
    matchLabels:
      app: master-app
  replicas: 1
  template:
    metadata:
      labels:
        app: master-app
    spec:
      tolerations:
      - key: sgx.intel.com/epc
        operator: Exists
        effect: NoSchedule
      containers:
      - name: master-python-graphene
        image: 10.239.45.10/arda/intelanalytics/analytics-zoo-ppml-trusted-realtime-ml-scala-graphene:0.12.0-SNAPSHOT
        command: ["/bin/sh","-c"]
        args: ["bash /ppml/trusted-realtime-ml/start-all-but-flink.sh | tee /ppml/trusted-realtime-ml/log; tail -f /dev/null"]
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 10
            sgx.intel.com/epc: ${EPC_MEM}
          limits:
            cpu: 12
            sgx.intel.com/epc: ${EPC_MEM}
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: dev-gsgx
            mountPath: /dev/gsgx
          - name: entry
            mountPath: /ppml/trusted-realtime-ml/start-all-but-flink.sh
          - name: aesm-socket
            mountPath: /var/run/aesmd/aesm.socket
          - name: enclave-keys
            mountPath: /graphene/Pal/src/host/Linux-SGX/signer/enclave-key.pem
          - name: redis-secure-keys
            mountPath: /ppml/trusted-realtime-ml/redis/work/keys
          - name: redis-secure-password
            mountPath: /ppml/trusted-realtime-ml/redis/work/password
          - name: java-secure-keys
            mountPath: /ppml/trusted-realtime-ml/java/work/keys
          - name: java-secure-password
            mountPath: /ppml/trusted-realtime-ml/java/work/password
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev-gsgx
        hostPath:
          path: /dev/gsgx
      - name: aesm-socket
        hostPath:
          path: /var/run/aesmd/aesm.socket
      - name: enclave-keys
        hostPath:
          path: /home/sdp/yiding/enclave-key/enclave-key.pem
      - name: entry
        hostPath:
          path: /home/sdp/yiding/intel-sgx-plugin/start-all-but-flink.sh
      - name: redis-secure-keys
        secret:
          secretName: ssl-keys
      - name: redis-secure-password
        secret:
          secretName: ssl-password
      - name: java-secure-keys
        secret:
          secretName: ssl-keys
      - name: java-secure-password
        secret:
          secretName: ssl-password
