## Analytics-zoo Cluster Serving

model:
  # model path must be set
  path: /opt/work/model/
data:
  # default, localhost:6379
  src: 
  # default, 3, 224, 224
  image_shape:
params:
  # default, 4
  batch_size:
  # default, 1
  top_n:
spark:
  # default, local[*]
  master:
  # default, 4g
  driver_memory: 16g
  # default, 1g
  executor_memory: 128g
  # default, 1
  num_executors:
  # default, 4
  executor_cores:
  # default, 4
  total_executor_cores:
