FROM ubuntu:18.04

MAINTAINER The Analytics Zoo Authors https://github.com/intel-analytics/analytics-zoo

WORKDIR /opt/work

ARG SPARK_VERSION=2.4.3 
ARG BIGDL_VERSION=0.10.0
ARG ZOO_VERSION=0.7.0-SNAPSHOT

ENV SPARK_HOME		/opt/work/spark-${SPARK_VERSION}
ENV JAVA_HOME		/opt/jdk
ENV PATH		${JAVA_HOME}/bin:${PATH}
ENV ZOO_JAR		analytics-zoo-bigdl_${BIGDL_VERSION}-spark_${SPARK_VERSION}-${ZOO_VERSION}-jar-with-dependencies.jar

RUN apt-get update && \
    apt-get install -y apt-utils vim curl nano wget unzip maven git && \
    apt-get install -y gcc g++ make && \
#python
    apt-get install -y python3-minimal && \
    apt-get install -y build-essential python3 python3-setuptools python3-dev python3-pip && \
    pip3 install --upgrade pip && \
    pip install --upgrade setuptools && \
    pip install tensorboard && \
#java
    wget https://build.funtoo.org/distfiles/oracle-java/jdk-8u152-linux-x64.tar.gz && \
    gunzip jdk-8u152-linux-x64.tar.gz && \
    tar -xf jdk-8u152-linux-x64.tar -C /opt && \
    rm jdk-8u152-linux-x64.tar && \
    ln -s /opt/jdk1.8.0_152 /opt/jdk && \
#redis
    wget http://download.redis.io/releases/redis-5.0.5.tar.gz && \
    tar xzf redis-5.0.5.tar.gz && \
    rm redis-5.0.5.tar.gz && \
    cd redis-5.0.5 && \
    make && \
    echo "bind 0.0.0.0" >> /opt/work/redis-5.0.5/redis.conf && \
    cd .. && \
#spark
    wget https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop2.7.tgz && \
    tar -zxvf spark-${SPARK_VERSION}-bin-hadoop2.7.tgz && \
    mv spark-${SPARK_VERSION}-bin-hadoop2.7 spark-${SPARK_VERSION} && \
    rm spark-${SPARK_VERSION}-bin-hadoop2.7.tgz && \
#spark-redis
    wget https://oss.sonatype.org/content/repositories/public/com/redislabs/spark-redis/2.4.0/spark-redis-2.4.0-jar-with-dependencies.jar

ADD ./scripts/*.sh /opt/work/
RUN chmod a+x /opt/work/*.sh
RUN /opt/work/download-analytics-zoo.sh

CMD ["/opt/work/zoo-cluster-serving.sh"]


