#!/usr/bin/bash

export MASTER=YOUR_MASTER_IP
export WORKERS=(YOUR_WORKER_IP_1 YOUR_WORKER_IP_2 YOUR_WORKER_IP_3)

export TRUSTED_BIGDATA_ML_DOCKER=10.239.45.10/arda/intelanalytics/bigdl-ppml-trusted-big-data-ml-python-graphene:0.14-SNAPSHOT

export SOURCE_ENCLAVE_KEY_PATH=YOUR_LOCAL_ENCLAVE_KEY_PATH
export SOURCE_KEYS_PATH=YOUR_LOCAL_KEYS_PATH
export SOURCE_SECURE_PASSWORD_PATH=YOUR_LOCAL_SECURE_PASSWORD_PATH
export SOURCE_DATA_PATH=YOUR_LOCAL_DATA_PATH

export BDL_PPML_PATH=/opt/bigdl-ppml
export ENCLAVE_KEY_PATH=$BDL_PPML_PATH/enclave-key.pem
export KEYS_PATH=$BDL_PPML_PATH/keys
export SECURE_PASSWORD_PATH=$BDL_PPML_PATH/password
export DATA_PATH=$BDL_PPML_PATH/data
