#!/usr/bin/python

from shutil import copyfile
import os
import urllib.request

from zoo.serving.server import ClusterServing

serving = ClusterServing()

if not os.path.exists('model'):
    os.mkdir('model')

SPARK_REDIS_JAR = 'spark-redis-2.4.0-jar-with-dependencies.jar'

if not os.path.exists(SPARK_REDIS_JAR):
    print("Downloading spark-redis dependency...")
    urllib.request.urlretrieve('https://oss.sonatype.org/content/repositories/'
                               'public/com/redislabs/spark-redis/2.4.0/'
                               + SPARK_REDIS_JAR,

                               SPARK_REDIS_JAR)
print("All environments for Cluster Serving are ready perfectly.")
