#!/usr/bin/env bash

# Copyright 2018 Analytics Zoo Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if (( $# < 2)); then
  echo "getting $* $#"
  echo "Bad parameters. Usage example: bash get_nlp_architect /tmp/nlp_architect/ 0.3.1"
  exit -1
fi

DEST_DIR=$1
echo "DEST_DIR: $DEST_DIR"
VERSION=$2
echo "NLP_ARCHITECT_VERSION: $VERSION"

rm -rf $DEST_DIR/*

GET_COMMAND="wget https://github.com/NervanaSystems/nlp-architect/archive/v${VERSION}.zip -P $DEST_DIR"

echo "Running: $GET_COMMAND"
$GET_COMMAND

exit_status=$?
if [ $exit_status -ne 0 ];
then
    rm -rf ${DEST_DIR}
    echo "Fail to get nlp-architect package from GitHub."
    exit $exit_status
fi

cd ${DEST_DIR}
mkdir sources
unzip v${VERSION}.zip -d sources
cd sources/nlp-architect-${VERSION}
mv nlp_architect/ ../
cd ${DEST_DIR}
rm -rf sources/nlp-architect-${VERSION}