#!/usr/bin/env bash

# Copyright 2018 Analytics Zoo Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


DEST_DIR=$1
echo "DEST_DIR: $DEST_DIR"

rm -rf $DEST_DIR/*/

echo "Fetching Libtorch"
GET_COMMAND="wget -nc https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-latest.zip -P $DEST_DIR"
echo "Running: $GET_COMMAND"
$GET_COMMAND
exit_status=$?
if [ $exit_status -ne 0 ];
then
    rm -rf $DEST_DIR/*/
    echo "Failed to get libtorch package from pytorch."
    exit $exit_status
fi

