#!/usr/bin/env bash

# Copyright 2018 Analytics Zoo Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This script generates the build info for zoo and places it into the zoo-version-info.properties file.
# Arguments:
#   build_tgt_directory - The target directory where properties file would be created. [./zoo/target/extra-resources]
#   spark_version - The version of spark currently built against
#   scala_version - The version of scala currently built against
#   java_version - The version of java currently built against

RESOURCE_DIR="$1"
mkdir -p "$RESOURCE_DIR"
ZOO_BUILD_INFO="${RESOURCE_DIR}"/zoo-version-info.properties

echo_build_properties() {
  echo analytics_zoo_verion=$1
  echo spark_version=$2
  echo scala_version=$3
  echo java_version=$4
}

echo_build_properties $2 $3 $4 $5 > "$ZOO_BUILD_INFO"
