site_name: Analytics Zoo
theme: null
extra_css: [extra.css]
theme_dir: mkdocs_windmill 
repo_name: 'Fork on GitHub '
repo_url: 'https://github.com/intel-analytics/analytics-zoo'
google_analytics: ['UA-125166209-1', 'analytics-zoo.github.io']
extra:
    version: latest
    article_nav_top: false
    article_nav_bottom: false

pages:
- Overview: index.md 
- Releases: 
  - Download: release-download.md 
  - Documentation: release-docs.md
- User Guide:
  - Python:
    - Install: PythonUserGuide/install.md
    - Run: PythonUserGuide/run.md
    - Examples: PythonUserGuide/examples.md
    - FAQ: PythonUserGuide/python-faq.md
  - Scala: 
    - Install: ScalaUserGuide/install.md
    - Run: ScalaUserGuide/run.md
    - Examples: ScalaUserGuide/examples.md
- Programming Guide: 
  - Pipeline APIs:
    - DataFrame and ML Pipeline: ProgrammingGuide/nnframes.md
    - Autograd: ProgrammingGuide/autograd.md
    - Transfer Learning: ProgrammingGuide/transferlearning.md
    - Model Serving: ProgrammingGuide/inference.md
    - Distributed Tensoflow on Spark/BigDL: ProgrammingGuide/tensorflow.md
  - Feature Engineering:
    - Working with Images: ProgrammingGuide/workingwithimages.md
    - Working with Texts: ProgrammingGuide/workingwithtexts.md
  - Built-in Models:
    - Object Detection API: ProgrammingGuide/object-detection.md
    - Image Classification API: ProgrammingGuide/image-classification.md
    - Text Classification API: ProgrammingGuide/text-classification.md
    - Recommendation API: ProgrammingGuide/recommendation.md
    - Anomaly Detection API: ProgrammingGuide/anomaly-detection.md
    - Text Matching API: ProgrammingGuide/text-matching.md
    - Sequence to Sequence API: ProgrammingGuide/seq2seq.md
  - Reference Use Cases: ProgrammingGuide/usercases-overview.md
- White Paper:
  - BigDL: wp-bigdl.md
- API Guide:
  - Pipeline APIs:
    - NNFrames: APIGuide/PipelineAPI/nnframes.md
    - Autograd-Math: APIGuide/PipelineAPI/math.md
    - Autograd-Variable: APIGuide/PipelineAPI/variable.md
    - Net: APIGuide/PipelineAPI/net.md
    - Inference: APIGuide/PipelineAPI/inference.md
  - Feature Engineering:
    - FeatureSet: APIGuide/FeatureEngineering/featureset.md
    - Relation: APIGuide/FeatureEngineering/relation.md
    - Image: APIGuide/FeatureEngineering/image.md
    - Text: APIGuide/FeatureEngineering/text.md
  - Models:
    - Object Detection: APIGuide/Models/object-detection.md
    - Image Classification: APIGuide/Models/image-classification.md
    - Text Classification: APIGuide/Models/text-classification.md
    - Recommendation: APIGuide/Models/recommendation.md
    - Anomaly Detection: APIGuide/Models/anomaly-detection.md
    - Text Matching: APIGuide/Models/text-matching.md
    - Sequence to Sequence: APIGuide/Models/seq2seq.md
- Keras-Style API Guide:
  - Python Guide: KerasStyleAPIGuide/keras-api-python.md
  - Scala Guide: KerasStyleAPIGuide/keras-api-scala.md
  - Layers:
    - Activation: KerasStyleAPIGuide/Layers/activation.md
    - Initialization: KerasStyleAPIGuide/Layers/initialization.md
    - Core Layers: KerasStyleAPIGuide/Layers/core.md
    - Convolutional Layers: KerasStyleAPIGuide/Layers/convolutional.md
    - Pooling Layers: KerasStyleAPIGuide/Layers/pooling.md
    - Recurrent Layers: KerasStyleAPIGuide/Layers/recurrent.md
    - Normalization Layers: KerasStyleAPIGuide/Layers/normalization.md
    - Embedding Layers: KerasStyleAPIGuide/Layers/embedding.md
    - Dropout Layers: KerasStyleAPIGuide/Layers/dropout.md
    - Advanced Activations: KerasStyleAPIGuide/Layers/advanced-activation.md
    - Layer Wrappers: KerasStyleAPIGuide/Layers/wrappers.md
  - Optimization:
    - Train, evaluate or predict a model: KerasStyleAPIGuide/Optimization/training.md
    - Optimizers: KerasStyleAPIGuide/Optimization/optimizers.md
    - Objectives: KerasStyleAPIGuide/Optimization/objectives.md
#- Keras2-Style API Guide:
#  - Python Guide: Keras2StyleAPIGuide/keras-api-python.md
#  - Scala Guide: Keras2StyleAPIGuide/keras-api-scala.md
#  - Layers:
#    - Activation: Keras2StyleAPIGuide/Layers/activation.md
#    - Initialization: Keras2StyleAPIGuide/Layers/initialization.md
#    - Core Layers: Keras2StyleAPIGuide/Layers/core.md
#    - Convolutional Layers: Keras2StyleAPIGuide/Layers/convolutional.md
#    - Pooling Layers: Keras2StyleAPIGuide/Layers/pooling.md
#    - Merge Layers: Keras2StyleAPIGuide/Layers/merge.md
#    - Recurrent Layers: Keras2StyleAPIGuide/Layers/recurrent.md
#    - Normalization Layers: Keras2StyleAPIGuide/Layers/normalization.md
#    - Embedding Layers: Keras2StyleAPIGuide/Layers/embedding.md
#    - Dropout Layers: Keras2StyleAPIGuide/Layers/dropout.md
#    - Advanced Activations: Keras2StyleAPIGuide/Layers/advanced-activation.md
#    - Layer Wrappers: Keras2StyleAPIGuide/Layers/wrappers.md
#  - Optimization:
#    - Train, evaluate or predict a model: Keras2StyleAPIGuide/Optimization/training.md
#    - Optimizers: Keras2StyleAPIGuide/Optimization/optimizer.md
#    - Losses: Keras2StyleAPIGuide/Optimization/loss.md
- Powered by: powered-by.md
- FAQ and Known Issues: known-issues.md
