site_name: Analytics-Zoo Project
theme: null
extra_css: [extra.css]
theme_dir: mkdocs_windmill 
repo_name: 'Fork on GitHub '
repo_url: 'https://github.com/intel-analytics/analytics-zoo'
extra:
    version: latest
    article_nav_top: false
    article_nav_bottom: false


pages:
- Overview: 
  - What is Zoo and Why: index.md 
  - Getting Help: gettinghelp.md
- Releases: 
  - Download: release-download.md 
  - Documentation: release-docs.md
- Getting Started: getting-started.md
- Scala User Guide: 
  - Examples: ScalaUserGuide/examples.md
  - Model API: ScalaUserGuide/modelapi.md
  - Pipeline API:
    - Keras-Style: ScalaUserGuide/PipelineAPI/keras-style.md
    - NNFrames: ScalaUserGuide/PipelineAPI/nnframes.md
- Python User Guide: 
  - Install:
    - From pip: PythonUserGuide/InstallAndRun/install-from-pip.md
  - Run:
    - After pip install: PythonUserGuide/InstallAndRun/run-from-pip.md
  - Examples: PythonUserGuide/python-examples.md
  - Model API: PythonUserGuide/model-api.md
  - Pipeline API:
    - Keras: PythonUserGuide/PipelineAPI/keras.md
    - NNFrames: PythonUserGuide/PipelineAPI/nnframes.md
- Programming Guide: programming-guide.md
- Notebooks: 
  - Scala: Notebooks/scala.md
  - Python: Notebooks/python.md
- Powered by: powered-by.md
- FAQ and Known Issues: known-issues.md
