site_name: Analytics Zoo
theme: null
extra_css: [extra.css]
theme_dir: mkdocs_windmill 
repo_name: 'Fork on GitHub '
repo_url: 'https://github.com/intel-analytics/analytics-zoo'
extra:
    version: latest
    article_nav_top: false
    article_nav_bottom: false

pages:
- Overview: index.md 
- Releases: 
  - Download: release-download.md 
  - Documentation: release-docs.md
- User Guide:
  - Python:
    - Install: PythonUserGuide/install.md
    - Run: PythonUserGuide/run.md
    - Examples: PythonUserGuide/examples.md
    - FAQ: PythonUserGuide/python-faq.md
  - Scala: 
    - Install: ScalaUserGuide/install.md
    - Run: ScalaUserGuide/run.md
    - Examples: ScalaUserGuide/examples.md
- Programming Guide: 
  - Pipeline APIs:
    - DataFrame and ML Pipeline: ProgrammingGuide/nnframes.md
    - Autograd: ProgrammingGuide/autograd.md
    - Transfer Learning: ProgrammingGuide/transferlearning.md
    - Inference: ProgrammingGuide/inference.md
  - Feature Engineering:
    - Working with Images: ProgrammingGuide/workingwithimages.md
  - Built-in Models:
    - Object Detection API: ProgrammingGuide/object-detection.md
    - Image Classification API: ProgrammingGuide/image-classification.md
    - Text Classification API: ProgrammingGuide/text-classification.md
    - Recommendation API: ProgrammingGuide/recommendation.md
  - Reference Use Cases:
    - Use Cases: ProgrammingGuide/usercases-overview.md
    - Anomaly Detection: ProgrammingGuide/anomaly-detection.md
- API Guide:
  - Pipeline APIs:
    - NNFrames: APIGuide/PipelineAPI/nnframes.md
    - Autograd-Math: APIGuide/PipelineAPI/math.md
    - Autograd-Variable: APIGuide/PipelineAPI/variable.md
    - Net: APIGuide/PipelineAPI/net.md
    - Inference: APIGuide/PipelineAPI/inference.md
  - Feature Engineering:
    - Image: APIGuide/FeatureEngineering/image.md
    - Preprocessing: APIGuide/FeatureEngineering/preprocessing.md
  - Models:
    - Object Detection: APIGuide/Models/object-detection.md
    - Image Classification: APIGuide/Models/image-classification.md
    - Text Classification: APIGuide/Models/text-classification.md
    - Recommendation: APIGuide/Models/recommendation.md
- Keras2-Style API Guide:
  - Python Guide: Keras2StyleAPIGuide/keras-api-python.md
  - Scala Guide: Keras2StyleAPIGuide/keras-api-scala.md
  - Layers:
    - Activation: Keras2StyleAPIGuide/Layers/activation.md
    - Initialization: Keras2StyleAPIGuide/Layers/initialization.md
    - Core Layers: Keras2StyleAPIGuide/Layers/core.md
    - Convolutional Layers: Keras2StyleAPIGuide/Layers/convolutional.md
    - Pooling Layers: Keras2StyleAPIGuide/Layers/pooling.md
    - Merge Layers: Keras2StyleAPIGuide/Layers/merge.md
    - Recurrent Layers: Keras2StyleAPIGuide/Layers/recurrent.md
    - Normalization Layers: Keras2StyleAPIGuide/Layers/normalization.md
    - Embedding Layers: Keras2StyleAPIGuide/Layers/embedding.md
    - Dropout Layers: Keras2StyleAPIGuide/Layers/dropout.md
    - Advanced Activations: Keras2StyleAPIGuide/Layers/advanced-activation.md
    - Layer Wrappers: Keras2StyleAPIGuide/Layers/wrappers.md
  - Optimization:
    - Train, evaluate or predict a model: Keras2StyleAPIGuide/Optimization/training.md
    - Optimizers: Keras2StyleAPIGuide/Optimization/optimizer.md
    - Losses: Keras2StyleAPIGuide/Optimization/loss.md
- Powered by: powered-by.md
- FAQ and Known Issues: known-issues.md
