apiVersion: v1
kind: Service
metadata:
  name: {{ template "analytics-zoo-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.AnalyticsZoo.Component }}"
spec:
  type: {{ .Values.AnalyticsZoo.ServiceType }}
  ports:
  - name: http
    port: {{ .Values.AnalyticsZoo.ServicePort }}
    targetPort: {{ .Values.AnalyticsZoo.ContainerPort }}
    protocol: TCP
  selector:
    component: "{{ .Release.Name }}-{{ .Values.AnalyticsZoo.Component }}"
