apiVersion: v1
kind: Service
metadata:
  name: {{ template "analytics-zoo-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
spec:
  type: {{ .Values.ServiceType }}
  ports:
  - name: http
    port: {{ .Values.ServicePort }}
    targetPort: {{ .Values.ContainerPort }}
    protocol: TCP
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
