{{ $persistence := .Values.Persistence }}
{{- if $persistence.Enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "analytics-zoo-fullname" . }}-notebook
spec:
  accessModes:
    - {{ $persistence.AccessMode | quote }}
  resources:
    requests:
      storage: {{ $persistence.Size | quote }}
{{- if $persistence.StorageClass }}
{{- if (eq "-" $persistence.StorageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ $persistence.StorageClass }}"
{{- end }}
{{- end }}
{{- end }}